import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/components/Header';

import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.scss'
import { Footer } from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gabriel Pessanha',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        />
      </head>
      <body  className={`${inter.className} backgroundBody`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
